language: scala
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
script:
- sbt "^^ ${SBT_VERSION}" scripted
matrix:
  include:
  - jdk: openjdk7
    env: SBT_VERSION="0.13.17"
  - jdk: oraclejdk8
    env: SBT_VERSION="1.1.6"
  - jdk: openjdk11
    env: SBT_VERSION="1.1.6"
